package com.japanese.lessons.models;

public enum ETargetType {
    MANGA_TABLE,
    IMAGE_TABLE,
    REWARD_TABLE,
    EXERCISE_TABLE,
    QUESTION_TABLE,
    GUIDANCE_TABLE,
    DYNAMIC_ROW_TABLE,
    EXERCISE_QUESTION,
    EXERCISE_SELECT,
    EXERCISE_COLOCATE,
    EXERCISE_FACT,
    EXERCISE_MULTIPLE_ANSWER_QUESTION,
    MANGA_DIALOGUE,
    IMAGES_TOGETHER,
    STUDY_CONTENT_WORDS,
    STUDY_CONTENT_PHRASES,
}
